#docker-compose.yml
version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - my_network
    restart: on-failure
    env_file:
      - .env

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: producer-1
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - my_network
    restart: on-failure
    entrypoint: sh -c "echo 'Waiting for Kafka...'; while ! nc -z kafka 9092; do sleep 2; done; echo 'Kafka is ready. Starting producer.'; python kafka_env/producer.py"
    env_file:
      - kafka_env/.env

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer-1
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - my_network
    restart: on-failure
    env_file:
      - kafka_env/.env

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - my_network
volumes:
  kafka_data:
networks:
  my_network:
    driver: bridge
