FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && \
    apt-get install -y netcat-traditional && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY kafka_env/ kafka_env/
RUN pip install kafka-python python-dotenv
CMD ["python", "kafka_env/producer.py"]
